version: "3.8"

services:
  app:
    build: .
    container_name: gerenciamento_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bancodeobjetos
      MYSQL_USER: Admin
      MYSQL_PASSWORD: "Mudar@1234"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
