version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Admin1234@$$"
      MYSQL_DATABASE: "objetos_gerenciar"
      MYSQL_USER: "Admin"
      MYSQL_PASSWORD: "Mudar1234@$$"
    ports:
      - "3308:3306" # Externo:Interno
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dbnet

volumes:
  db_data:

networks:
  dbnet:
