version: "3.8"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bancodeobjetos
      MYSQL_USER: Admin
      MYSQL_PASSWORD: "Mudar@1234"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: seuusuario/gobjetos:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: Admin
      DB_PASSWORD: "Mudar@1234"
      DB_NAME: bancodeobjetos

volumes:
  mysql_data:
