version: "3.8"

services:
  node:
    image: stemas22122007/gobjetos:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bancodeobjetos
      MYSQL_USER: Admin
      MYSQL_PASSWORD: "Mudar@1234"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./site:/usr/share/nginx/html:ro
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  depends_on:
    - node

volumes:
  mysql_data:
