version: "3.8"

services:
  app:
    image: stemas22122007/gobjetos:latest
    env_file:
      - .env
    ports:
      - "3000:3000" # <-- isso permite acessar o site pelo navegador
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bancodeobjetos
      MYSQL_USER: Admin
      MYSQL_PASSWORD: "Mudar@1234"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any

volumes:
  mysql_data:
