version: "3.8"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql # Altere conforme o hostname correto do seu banco
      DB_USER: Admin
      DB_PASSWORD: "Mudar1234@$$"
      DB_NAME: objetos_gerenciar
    networks:
      - objetos_gerenciar_rede

networks:
  objetos_gerenciar_rede:
    external: true
