-- MySQL Script generated by MySQL Workbench
-- Fri Apr 25 16:36:14 2025
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bancodeobjetos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancodeobjetos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancodeobjetos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bancodeobjetos` ;

-- -----------------------------------------------------
-- Table `bancodeobjetos`.`piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodeobjetos`.`piso` (
`idPiso` INT NOT NULL,
`NomePiso` VARCHAR(45) NULL DEFAULT NULL,
PRIMARY KEY (`idPiso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancodeobjetos`.`tiposala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodeobjetos`.`tiposala` (
`idTipoSala` INT NOT NULL,
`NomeTipoSala` VARCHAR(45) NULL DEFAULT NULL,
PRIMARY KEY (`idTipoSala`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancodeobjetos`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodeobjetos`.`sala` (
`idSala` INT NOT NULL,
`NomeSala` VARCHAR(45) NULL DEFAULT NULL,
`Piso_idPiso` INT NOT NULL,
`TipoSala_idTipoSala` INT NOT NULL,
PRIMARY KEY (`idSala`, `Piso_idPiso`, `TipoSala_idTipoSala`),
INDEX `fk_Sala_Piso1_idx` (`Piso_idPiso` ASC) VISIBLE,
INDEX `fk_Sala_TipoSala1_idx` (`TipoSala_idTipoSala` ASC) VISIBLE,
CONSTRAINT `fk_Sala_Piso1`
FOREIGN KEY (`Piso_idPiso`)
REFERENCES `bancodeobjetos`.`piso` (`idPiso`),
CONSTRAINT `fk_Sala_TipoSala1`
FOREIGN KEY (`TipoSala_idTipoSala`)
REFERENCES `bancodeobjetos`.`tiposala` (`idTipoSala`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancodeobjetos`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodeobjetos`.`status` (
`idStatus` INT NOT NULL,
`Nome` VARCHAR(45) NULL DEFAULT NULL,
PRIMARY KEY (`idStatus`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancodeobjetos`.`tipoobjeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodeobjetos`.`tipoobjeto` (
`idTipoObjeto` INT NOT NULL,
`NomeDoTipo` VARCHAR(45) NULL DEFAULT NULL,
PRIMARY KEY (`idTipoObjeto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bancodeobjetos`.`objeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancodeobjetos`.`objeto` (
`codigo` INT NOT NULL,
`TipoObjeto_idTipoObjeto` INT NOT NULL,
`Status_idStatus` INT NOT NULL,
`Sala_idSala` INT NOT NULL,
`Complemento` VARCHAR(100) NULL DEFAULT NULL,
PRIMARY KEY (`codigo`, `TipoObjeto_idTipoObjeto`, `Status_idStatus`, `Sala_idSala`),
INDEX `fk_Objeto_TipoObjeto_idx` (`TipoObjeto_idTipoObjeto` ASC) VISIBLE,
INDEX `fk_Objeto_Status1_idx` (`Status_idStatus` ASC) VISIBLE,
INDEX `fk_Objeto_Sala1_idx` (`Sala_idSala` ASC) VISIBLE,
CONSTRAINT `fk_Objeto_Sala1`
FOREIGN KEY (`Sala_idSala`)
REFERENCES `bancodeobjetos`.`sala` (`idSala`),
CONSTRAINT `fk_Objeto_Status1`
FOREIGN KEY (`Status_idStatus`)
REFERENCES `bancodeobjetos`.`status` (`idStatus`),
CONSTRAINT `fk_Objeto_TipoObjeto`
FOREIGN KEY (`TipoObjeto_idTipoObjeto`)
REFERENCES `bancodeobjetos`.`tipoobjeto` (`idTipoObjeto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;